spring:
    application:
        name: JW.Abulance-Services
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: validate
            naming: 
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/ambulance_service
        username: postgres
        password: 12345

